### ISSUE TITLE
GDSC ResponseCurve data is missing Biosample edges

### ISSUE THREAD

**Issue by buchanae** [bmeg/bmeg-etl#101]
```
curl -X POST -H "Content-Type: application/json" http://10.96.11.144/query/ResponseCurve -d '[["where", {"source": "ccle"}], ["to", "responseFor", "Biosample"]]' | head -n1

{"gid":"biosample:ccle:NCIH1792_LUNG","CCLE name":"NCIH1792_LUNG","Cell line aliases":"H1792","Cell line primary name":"NCI-H1792","Expression ...


curl -X POST -H "Content-Type: application/json" http://10.96.11.144/query/ResponseCurve -d '[["where", {"source": "gdsc"}], ["to", "responseFor", "Biosample"]]'
<empty response>

curl -X POST -H "Content-Type: application/json" http://10.96.11.144/query/ResponseCurve -d '[["groupCount", "source"]]'
{"key":"gdsc","count":86910}
{"key":"ccle","count":329889}
```

The first query demonstrates that the query works correctly for "ccle". The second query demonstrates that no results are returned for "gdsc". The third query demonstrates the available sources.

Is it expected that GDSC response curves aren't linked to biosamples?

**Comment by prismofeverything** [comment]
Looks like we never pulled them in? This shows just getting response
curves:
https://github.com/biostream/bmeg-etl/blob/master/bmeg.processes.yaml#L131-L154

Happy to pull them in if we find where these cell lines came from.

**Comment by buchanae** [comment]
Looks like we have the cell line metadata spreadsheet already (`CELL_LINES: source/gdsc/Cell_Lines_Details.xlsx`), and each response curve has a `sample` field matching that spreadsheet.

**Comment by prismofeverything** [comment]
Cool, so really it is just the transform we need to update to emit the
samples:
https://github.com/biostream/gdsc-transform/blob/master/gdsc-convert.py

**Comment by adamstruck** [comment]
We are tracking the latest connectivity problems in #212
