### ISSUE TITLE
Add Cell line vertex type?

### ISSUE THREAD

**Issue by buchanae** [bmeg/bmeg-etl#107]
Have you guys considered adding a cell line vertex type? This might provide some connection between datasets. For example, I'd like to get expression data in all PC3 cell line datasets across ccle, tcga, and future expression datasets.

This could be further abstracted to tissue type, e.g. I'd like to get all expression data related to "lung".

**Comment by kellrott** [comment]
Settled on using fake Individuals for cell lines
