### ISSUE TITLE
Genomic intervals: standardize on representation (0 vs 1 based, open vs closed)

### ISSUE THREAD

**Issue by buchanae** [bmeg/bmeg-etl#118]
Like gene/feature names/IDs, a variety of genomic interval representations plague the bioinformatics world. Having to convert between and worry about multiple types of intervals is a burden on analysis, and getting it wrong can have big consequences.

BMEG should aim to have all genomic positions and intervals use the same coordinate system and representation.

I don't have a strong preference which; being a programmer I'm fond of 0-based half-open.

A resource describing the minutia: http://genome.ucsc.edu/blog/the-ucsc-genome-browser-coordinate-counting-systems/

**Comment by kellrott** [comment]
@bwalsh please check various pieces of data, to do a sanity check, and then write down the standard for the docs
