### ISSUE TITLE
TCGA BRCA Individuals off by one?

### ISSUE THREAD

**Issue by buchanae** [bmeg/bmeg-etl#123]
```
In [44]: q.where(aql.eq("_label", "Individual")).where(aql.eq("source", "tcga")).where(aql.eq("disease_code", "BRCA")).count().execute()
Out[44]: [<AttrDict({u'count': 1097})>]
```

<img width="344" alt="screen shot 2018-05-29 at 2 43 59 pm" src="https://user-images.githubusercontent.com/262647/40687217-c4af8290-634e-11e8-9ec2-88d9ec2af8a0.png">

BMEG shows 1907 but GDC shows 1098?

**Comment by buchanae** [comment]
I got the list of cases from GDC and compared it to BMEG:
```
res = O.V().where(aql.eq("_label", "Individual")).where(aql.eq("source", "tcga")).where(aql.eq("disease_code", "BRCA"))
ids = set()
for row in res:
    ids.add(row.data.bcr_patient_barcode)
    
print(len(ids))
set(gdc_case_list) - ids
```

This is the missing case: `TCGA-BH-A0B2`

**Comment by bwalsh** [comment]
@buchanae is this still an issue?
