### ISSUE TITLE
G2P Evidence vertices don't link to Pubmed vertices

### ISSUE THREAD

**Issue by adamstruck** [bmeg/bmeg-etl#127]
The `evidenceFor` edge type uses the form: `pubmed:http://www.ncbi.nlm.nih.gov/pubmed/23526464` in the `from` and `to` fields.

The `Pubmed` vertex type uses the form `pubmed:23526464` as its `gid`

**Comment by bwalsh** [comment]
@adamstruck Does this bug refer to the current g2p?   Currently we are linking to `Publication:http...`

**Comment by adamstruck** [comment]
Yes this still applies since the G2P PR (https://github.com/bmeg/bmeg-etl/pull/168) and pubmed PR (https://github.com/bmeg/bmeg-etl/pull/167) are still not aligned.
