### ISSUE TITLE
variantIn edges reference incorrect variant gids

### ISSUE THREAD

**Issue by adamstruck** [bmeg/bmeg-etl#131]
There appears to be an issue with the `variantIn` edges. Most of them are not referencing `Variant` vertices.  I think the `from` fields are not being formatted correctly. 

Example `variantIn`:

```
{
  "gid": "(variant:GRCh37:10:123810032:123810032:C:C,T)--variantIn->(gene:ENSG00000138162)",
  "from": "variant:GRCh37:10:123810032:123810032:C:C,T",
  "label": "variantIn",
  "to": "gene:ENSG00000138162",
  "data": {
    "effects": "SNP",
    "gene": "ENSG00000138162",
    "bases": "C,T"
  }
}
```

And here is was the closest `Variant` vertex I found:
```
{
  "label": "Variant",
  "gid": "variant:GRCh37:10:123810032:123810032:C:C",
  "data": {
    "chromosome": "10",
    "referenceBases": "C",
    "referenceGenome": "GRCh37",
    "id": "GRCh37:10:123810032:123810032:C:C,T",
    "referenceName": "10",
    "start": 123810032,
    "alternateBases": "C",
    "end": 123810032
  }
}
```

**Comment by adamstruck** [comment]
Protograph is creating a `variantIn` edge for each object under `transcriptEffects`.  Here is an example `VariantAnnotation` message:

```
{
  "id": "GRCh37:2:179477551:179477551:C:A,C",
  "variantId": "GRCh37:2:179477551:179477551:C:A,C",
  "transcriptEffects": [
    {
      "featureId": "ENSG00000155657",
      "effects": [
        {
          "term": "SNP"
        }
      ],
      "alternateBases": "A,C"
    }
  ]
}
```

It looks like the transformer is wrong. I would have expected there to be some effect predicted for each alternate base rather than lumping everything together as we see above.

**Comment by adamstruck** [comment]
I think things may have gone gone awry here: https://github.com/biostream/variant-transform/commit/24cb7c87f90085219693edf4c5f10221c1f6f99c

**Comment by bwalsh** [comment]
@adamstruck can we close

**Comment by adamstruck** [comment]
Yep this is no longer an issue.
