### ISSUE TITLE
CCLE (or other cell line projects) do not record 'passage' id

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#176]
A cell line can have different `passages` ( given an original cell line, grow more in a dish, label that dish a passage - since any biological growth process can introduce variants)

COSMIC has a cell line id see COSS1287381  https://cancer.sanger.ac.uk/cell_lines/sample/overview?id=1287381

**Comment by adamstruck** [comment]
closing since this data is not available for CCLE / GDSC / CTRP
