### ISSUE TITLE
Verify GDC Diagnosis/Treatment retrieved

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#178]
@kellrott 
I've verified that we are retrieving and saving diagnosis and treatment.

However, the some treatment fields are null.

I spot checked the GDC portal and they are none as well.

**It is inconclusive if we should use the XML files instead.   Can you point me to them?**

 
![image](https://user-images.githubusercontent.com/47808/45193683-27ac0b80-b204-11e8-8b06-5bb655f029e2.png)

![image](https://user-images.githubusercontent.com/47808/45193723-588c4080-b204-11e8-85c2-8424705060b8.png)

**Comment by bwalsh** [comment]
Should we create an issue here https://github.com/NCI-GDC/gdcapi ?

**Comment by kellrott** [comment]
Yes. Not sure which is the right repo yet...
