### ISSUE TITLE
cell line `passages`

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#179]
A cell line can have different `passages` ( given an original cell line, grow more in a dish, label that dish a passage - since any biological growth process can introduce variants)

COSMIC has a cell line id see COSS1287381  https://cancer.sanger.ac.uk/cell_lines/sample/overview?id=1287381

**Comment by adamstruck** [comment]
I think `passage` can be captured as a property of the `Biosample` or `Aliquot` if it is available.

**Comment by adamstruck** [comment]
Duplicate of #176
