### ISSUE TITLE
Kallisto: Add Transcipt-Level TCGA RNAseq

### ISSUE THREAD

**Issue by michal-g** [bmeg/bmeg-etl#18]
available here: https://xenabrowser.net/datapages/?dataset=tcga_Kallisto_tpm&host=https://toil.xenahubs.net

useful since we are using the same Kallisto platform to get RNAseq from SMMART patients, so if we want to train models on TCGA to apply to these patients this is the data we'll want to use

**Comment by prismofeverything** [comment]
Okay circling around to this, thanks for the suggestion!

**Comment by kellrott** [comment]
Should probably be looking at https://osf.io/gqrz9/ which is the repo for the original Tatlow paper ( https://www.nature.com/articles/srep39259 ). Also has the CCLE data via the same pipeline.

**Comment by kellrott** [comment]
Fixed in #159
