### ISSUE TITLE
Simplify test code

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#187]
Capture requirements/patterns to simplify tests here...

**Comment by buchanae** [comment]
Here's one idea: all/most tests could just run the transformer on a test input file. The output would be compared against an expected output. If there are differences, then either the expected output file needs to change, or the transformer needs to change.

I think this could consolidate and remove a lot of python boilerplate that is currently doing setup, teardown, and in particular doing data assertions in python. We can probably do all of our data assertions with a simple file diff.

**Comment by bwalsh** [comment]
Good idea, interesting.  I had imagined that the pain point was on the setup ( transformers write to `outputs/...` and tests need to direct the transformers to write elsewhere  tests/unit/xxx/test/... , transformers read from `source/...` tests need to direct transformers to read from tests/unit/xxx/source )  That's the bit that seems verbose.  It could be resolved with some directory renaming/symlinking?
