### ISSUE TITLE
GTEX:  Expression->ExpressionOf->Aliquot.  `ExpressionOf` missing

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#188]
### Current bmeg-test graph missing `ExpressionOf` 

![image](https://user-images.githubusercontent.com/47808/45562172-73f7dc80-b7fe-11e8-83a6-6ee4f727725f.png)

### File is there on exacloud

```
head -1 ~/Downloads/gtex.ExpressionOf.Edge.json
{"_id": "(Expression:gtex:GTEX-1117F-0226-SM-5GZZ7)--ExpressionOf->(Aliquot:GTEX-1117F-0226-SM-5GZZ7)", "gid": "(Expression:gtex:GTEX-1117F-0226-SM-5GZZ7)--ExpressionOf->(Aliquot:GTEX-1117F-0226-SM-5GZZ7)", "label": "ExpressionOf", "from": "Expression:gtex:GTEX-1117F-0226-SM-5GZZ7", "to": "Aliquot:GTEX-1117F-0226-SM-5GZZ7", "data": {}}
```

### unclear if it failed to load?

* it would be useful to be able to access the loader log to verify

### Aliquots not present

* V("Aliquot:GTEX-1117F-0226-SM-5GZZ7") returns null
* no outputs/gtex/gtex.Aliquots.json exists

**Comment by bwalsh** [comment]
Ran ` python -m transform.gtex.samples -v`
spot checked gid, uploaded to swift

```
grep Aliquot:GTEX-1117F-0226-SM-5GZZ7 gtex.Aliquot.Vertex.json
{"_id": "Aliquot:GTEX-1117F-0226-SM-5GZZ7", "gid": "Aliquot:GTEX-1117F-0226-SM-5GZZ7", "label": "Aliquot", "data": {"aliquot_id": "GTEX-1117F-0226-SM-5GZZ7"}}

 ~/bin/swift upload -S 1073741824  bmeg/outputs/gtex *.json
outputs/gtex/gtex.Individual.Vertex.json
outputs/gtex/gtex.InProject.Edge.json
outputs/gtex/gtex.Aliquot.Vertex.json
outputs/gtex/gtex.AliquotFor.Edge.json
outputs/gtex/gtex.BiosampleFor.Edge.json
outputs/gtex/gtex.Biosample.Vertex.json
outputs/gtex/gtex.Project.Vertex.json
```

**Comment by bwalsh** [comment]
Looks like we resolved it.

![image](https://user-images.githubusercontent.com/47808/45574381-bb915f00-b824-11e8-8b80-3f09d223a937.png)


![image](https://user-images.githubusercontent.com/47808/45574429-db288780-b824-11e8-833b-995b429c5373.png)

**Comment by bwalsh** [comment]
@kellrott  can you review and close

**Comment by kellrott** [comment]
This looks good so far. Having some trouble viewing all of the data because of https://github.com/bmeg/grip/issues/143
