### ISSUE TITLE
GTEX: Tissue  ( Phenotype? )

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#189]
AFAIK, gtex maintains an association of sample to Tissue, but there is no link from either project, individual or sample to a concept of Phenotype (disease)

![image](https://user-images.githubusercontent.com/47808/45564818-7c541580-b806-11e8-892f-89f36a614655.png)

SMTS | Tissue Type, area from which the   tissue sample was taken.  This is a   parent value to SMTSD.
-- | --
SMTSD | Tissue Type, more specific   detail of tissue type

### Should we construct a phenotype?

*  i.e. "\<SMTS\> Cancer"
* e.g. "Brain Cancer" -> DOID:1319

**Comment by adamstruck** [comment]
Lets leave tissue as a property on Biosample.

**Comment by adamstruck** [comment]
"Healthy" as a phenotype?

**Comment by bwalsh** [comment]
@adamstruck Not seeing a 'healthy' ontology id
![image](https://user-images.githubusercontent.com/47808/45852341-2db9e600-bcf4-11e8-9e21-9eecfba378f6.png)
