### ISSUE TITLE
CCLE: Phenotype

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#190]
AFAIK, CCLE maintains an association of sample to Aliquot, but there is no link from either  aliquot or sample to a concept of Phenotype (disease)

![image](https://user-images.githubusercontent.com/47808/45565347-2c764e00-b808-11e8-992f-46777fe8bcad.png)

### Should we construct a phenotype?

*  i.e. "\<Histology | Hist Subtype1\>"
* e.g. "astrocytoma" -> DOID:3069

**Comment by adamstruck** [comment]
Yes, I think that we should construct a Phenotype in this case.
