### ISSUE TITLE
gtex.expression column count > 56K

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#195]
Noticed the transformation was slow

```
python -m transform.gtex.expression
rate: 1,000 emitted (3/sec)
```

+56K columns

```
head -1 Expression.Vertex.json | jq -r .data.values | wc -l
   56204
```

Is there an opportunity compress, perhaps by suppress values with 0?

**Comment by kellrott** [comment]
Suppressing the 0 and doing the subset of protein coding isoforms could be used. 

We need to test if https://github.com/bmeg/grip/pull/145 solves technical problems related to the datasize.
