### ISSUE TITLE
ccle: CallsetFor links to unknown aliquot vertices

### ISSUE THREAD

**Issue by adamstruck** [bmeg/bmeg-etl#203]
Example:

`Callset:ccle:SF8657_SKIN:None:variant)--CallsetFor->(Aliquot:SF8657_SKIN)`

**Comment by adamstruck** [comment]
For the example above I did not find any reference of that sample in `source/ccle/CCLE_sample_info_file_2012-10-18.txt`, but did confirm it is referenced in the MAF

**Comment by bwalsh** [comment]
I've double checked.  There are no references to those sample in the sample info file.  Also, broad does not seem to have any other sample associated with those cell lines.

```
$grep SF8657_SKIN CCLE_sample_info_file_2012-10-18.txt | wc -l 
0

$ grep SF8657_SKIN  ccle2maf_081117.txt | wc -l
      33
```

**Comment by bwalsh** [comment]
Unclear best path forward.  Suggest creating BioSample->Aliquot from maf transform into their own prefix  `maf.`BioSample.Vertex, etc.  and then let samples transform override.

**Comment by adamstruck** [comment]
Found another source for CCLE cell line metadata: https://depmap.org/portal/download/api/download/external?file_name=processed_portal_downloads%2Fdepmap-public-2018q3-cell-line-metadata-0bd2.2%2FDepMap-2018q3-celllines.csv

**Comment by bwalsh** [comment]
^^ implementing now

**Comment by adamstruck** [comment]
Possibly useful for id normalization:

ftp://ftp.sanger.ac.uk/pub/project/cancerrxgene/releases/current_release/GDSC-CCLE-CTRP_conversion.xlsx
