### ISSUE TITLE
graph connectivity results

### ISSUE THREAD

**Issue by adamstruck** [bmeg/bmeg-etl#212]
|  # Unconnected      |        Edge Label                  | 
|--------|--------------------------| 
| 79956  | "AlleleIn"               | 
| 444    | "CallsetFor"             | 
| 27825  | "DrugResponseIn"         | 
| 421326 | "ExonFor"                | 
| 511    | "ExpressionOf"           | 
| 30061  | "GeneOntologyAnnotation" | 
| 607    | "HasAlleleFeature"       | 
| 13     | "HasGeneFeature"         | 
| 28693  | "HasSupportingReference" | 
| 2      | "MinimalAlleleIn"        | 
| 5996   | "PFAMClanMember"         | 
| 34405  | "ProteinFor"             | 
| 138232 | "StructureFor"           | 
| 2719   | "TranscriptFor"          |

**Comment by adamstruck** [comment]
770,790 / 13,564,352 edges reference a vertex that does not exist

**Comment by bwalsh** [comment]
Re.  "HasAlleleFeature"  - should be in new file


```
{"From":"G2PAssociation:6801ec648545fc2e6a6a9af1370ee46249e12256","Gid":"(G2PAssociation:6801ec648545fc2e6a6a9af1370ee46249e12256)--HasAlleleFeature-\u003e(Allele:b386107073e53ba055c55b25f9d3b2eba4189f74)","Label":"HasAlleleFeature","To":"Allele:b386107073e53ba055c55b25f9d3b2eba4189f74","level":"error","msg":"To does not exist","time":"2018-09-26T21:45:35Z"}



grep b386107073e53ba055c55b25f9d3b2eba4189f74 Allele.Vertex.json
{"_id": "Allele:b386107073e53ba055c55b25f9d3b2eba4189f74", "gid": "Allele:b386107073e53ba055c55b25f9d3b2eba4189f74", "label": "Allele", "data": {"genome": "GRCh37", "chromosome": "12", "start": 57865493, "end": 57865493, "reference_bases": "A", "alternate_bases": "G", "annotations": {"maf": null, "mc3": null, "ccle": null, "myvariantinfo": null}}}
```

**Comment by bwalsh** [comment]
Re. DrugResponseIn
```
{"From":"DrugResponse:(5Z)-7-Oxozeaenol:A253_UPPER_AERODIGESTIVE_TRACT","Gid":"(DrugResponse:(5Z)-7-Oxozeaenol:A253_UPPER_AERODIGESTIVE_TRACT)--DrugResponseIn-\u003e(Biosample:A253_UPPER_AERODIGESTIVE_TRACT)","Label":"DrugResponseIn","To":"Biosample:A253_UPPER_AERODIGESTIVE_TRACT","level":"error","msg":"To does not exist","time":"2018-09-26T21:45:38Z"}
```

This looks similar to #203

**Comment by adamstruck** [comment]
Updated results from today (includes data generated by #213)

|  # Unconnected      |             Edge Label             | 
|--------|--------------------------| 
| 11345  | "AlleleIn"               | 
| 444    | "CallsetFor"             | 
| 27825  | "DrugResponseIn"         | 
| 511    | "ExpressionOf"           | 
| 28641  | "GeneOntologyAnnotation" | 
| 10     | "HasGeneFeature"         | 
| 28693  | "HasSupportingReference" | 
| 2      | "MinimalAlleleIn"        | 
| 5996   | "PFAMClanMember"         | 
| 21500  | "ProteinFor"             | 
| 138232 | "StructureFor"           |

**Comment by adamstruck** [comment]
Re:  "AlleleIn" edges

These 11,345 edges reference 256 gene vertices that do not exist

**Comment by bwalsh** [comment]
Re. MinimalAlleleIn
Also pointing at genes w/out GRCh37 equivalent

**Comment by bwalsh** [comment]
Unconnected | Edge Label | # Unconnected | improvement(neg. is good) | comment
-- | -- | -- | -- | --
79956 | "AlleleIn" | 11898 | -68058 | genes
444 | "CallsetFor" | 115 | -329 | ccle_callset
27825 | "DrugResponseIn" | 1325 | -26500 | ccle_callset ?
421326 | "ExonFor" | 0 | -421326 | done!
511 | "ExpressionOf" | 337 | -174 | ccle_callset ?
30061 | "GeneOntologyAnnotation" | 28641 | -1420 |  
607 | "HasAlleleFeature" | 0 | -607 | done!
13 | "HasGeneFeature" | 10 | -3 |  
28693 | "HasSupportingReference" | 28693 | 0 |  
2 | "MinimalAlleleIn" | 2 | 0 |  
5996 | "PFAMClanMember" | 5996 | 0 |  
  | PhenotypeOf | 7 | 7 |  
34405 | "ProteinFor" | 21500 | -12905 |  
138232 | "StructureFor" | 138232 | 0 |  
2719 | "TranscriptFor" | 0 | -2719 | done!

**Comment by bwalsh** [comment]
```grep "does not exist" check-graph.out | jq -c 'select(.level == "error" and .msg == "To does not exist")' | jq .Label | sort | uniq -c```

##  Unconnected   Edges


new_count | new_label | old_count | delta | Comment
-- | -- | -- | -- | --
9759 | COCAClusterFor |   | 9759 |  Individual
11898 | AlleleIn | 11345 | 553 | Gene
29178 | HasSupportingReference | 28693 | 485 | Pubs
10 | HasGeneFeature | 10 | 0 | Gene
2 | MinimalAlleleIn | 2 | 0 | Gene
21500 | ProteinFor | 21500 | 0 | Transcript
  | "CallsetFor" | 444 |   |  
  | "DrugResponseIn" | 27825 |   |  
  | "ExpressionOf" | 511 |   |  
28565 | GeneOntologyAnnotation | 28641 | -76 | Gene
  | "PFAMClanMember" | 5996 |   |  
  | "StructureFor" | 138232 |   |  

### comments

* Gene | There is no   ungapped mapping of this gene onto the GRCh37 assembly.
* Pubs | References other than pubmed
* Transcript | Transcript does not exist?
* Individual | TCGA-* does not exists e.g. TCGA-ZN-A9VP

**Comment by adamstruck** [comment]
The COCACluster vertices/edges should probably not be loaded into the graph. That was a data source we were thinking of using for CEDAR.

**Comment by adamstruck** [comment]
I think the disconnected ProteinFor edges are pointing to Transcripts on scaffolds. If that is the case, this issue could be resolved by changing the source GFF3 for the ensembl transform to `ftp://ftp.ensembl.org/pub/grch37/update/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.chr_patch_hapl_scaff.gff3.gz`.  I will run this later today to confirm.

**Comment by adamstruck** [comment]
Switching to `Homo_sapiens.GRCh37.87.chr_patch_hapl_scaff.gff3.gz` reduced the number of unconnected edges from 21500 to 17665.  It looks like the issue here is that the source used to generate `ProteinFor` edges is for GRCh38. 

Here is one example:

```
{"From":"Protein:ENSP00000483438","Gid":"(Protein:ENSP00000483438)--ProteinFor->(Transcript:ENST00000619796)","Label":"ProteinFor","To":"Transcript:ENST00000619796","level":"error","msg":"To does not exist","time":"2018-10-11T11:27:52-07:00"}
```

**Comment by bwalsh** [comment]
Drugs and diseases that have no official ontology

## Compounds

```
$ cat  outputs/compound/normalized.Compound.Vertex.json | jq -r .gid | grep ONTOLOGY | sed s/Compound:NO_ONTOLOGY~//  | sort
681640
81C6
81c6
9 immunoamino camptnetecin
9AC 9 Aminocamplotecian
A202171 Protocol
A4QN
ACT PEP3 KLH
AE 788
ATTAC
AZD
Anti necplatens
BCG
BX796
CAI (NABTT 9712)
CAI (NABTT 97212)
CAI NABIT 9712
CCNG
CMK
Chemo, Multi-Agent, NOS
Chemo, NOS
FMK
GOG 218
GOG182
Genentech Cpd 10
Gliadle Wafer
HG-5-113-01
HG-5-88-01
High dose ara-c
ICT-107
IL 12
IL 13
IOX2
JQ1 (1)
JQ1 (2)
JQ12
JW-7-24-1
JW-7-52-1
KIN001-236
KIN001-244
KIN001-260
KIN001-266
KIN001-270
Lymphocyte Infusion
MAB I 131
MAB I-131
MAB I131
MABI131
MAGI131-81c6
MAb I-131
MEDT 575
MPS-1-IN-1
MU81C6
Mayo 425-20
NPK76-II-72-1
Not otherwise specified
Not specified
O6B6
O6BG
PC2
PCB
PEP3 KLH
PLFE
Poly LCLC
QL-VIII-58
QL-X-138
QL-XI-92
QL-XII-47
QL-XII-61
QS11
R04929097
RBBX 01
Ras Inhibitor
Rhumab/Ind
SB52334
SCH 58500
SCH63666
SCH6636
Sovatenib
TL-1-85
TL-2-105
Temozolomoide
VNLG/124
Vamydex
WZ-1-84
WZ3105
XMD11-85h
XMD13-2
XMD14-99
XMD15-27
XMD8-85
ZG-10
anti neopastons
ch81c6
dcVax
mu81c6
rec MAGE 3-AS + AS15 ACS1 / Placebo Vaccine
rec MAGE3-AS+AS15 ASCI vs Placebo
recMAGE3-AS+AS15 ASCI/Placebo vaccine
recPRAME+AS15
recPRAME+AS15 ASCI
```
## Phenotypes
```
$ cat  outputs/phenotype/normalized.Phenotype.Vertex.json | jq -r .gid | grep ONTOLOGY | sed s/Phenotype:NO_ONTOLOGY~//  | sort
Ewings_sarcoma-peripheral_primitive_neuroectodermal_tumour
giant_cell_tumour
immortalized_epithelial
immortalized_fibroblast
rhabdoid_tumour
```

**Comment by adamstruck** [comment]
Remaining items are being tracked in specific issues.
