### ISSUE TITLE
source/ccle: incorrect / unused source files

### ISSUE THREAD

**Issue by adamstruck** [bmeg/bmeg-etl#226]
AFAIK the following files were replaced by updated versions:

* source/ccle/CCLE_sample_info_file_2012-10-18.txt
* source/ccle/ccle2maf_081117.txt

And we are missing the new sample info file we downloaded from DepMap and use in #216

**Comment by bwalsh** [comment]
Done. Thanks for the heads up

**Comment by adamstruck** [comment]
👍
