### ISSUE TITLE
json emitter gzip header

### ISSUE THREAD

**Issue by bwalsh** [bmeg/bmeg-etl#271]
By default, gzip writes filename and mtime into the header.
This has the effect or creating .gz files with different md5 hashes, even though the input is identical.

TODO in emitter,  set mtime to 0

```
gz = gzip.GzipFile(filename='', compresslevel=9, fileobj=open('mytest.gz', mode='wb'), mtime=0)
gz.write('dddddddddddddddddd')
gz.close()

```

**Comment by adamstruck** [comment]
___Note___: if you unzip the file produced in the example above and then gzip it again you end up with a different md5. It would be nice if we had a way to reproduce the same gzipped files from the command line after decompressing. 

```
gunzip mytest.gz
gzip -n -9 mytest
```
