### ISSUE TITLE
Edge Connecting drug response studies to profiled drugs

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#300]
When checking a cohort for different drug response profiles, the only way to know all of the tested drugs is something like
```
V("Project:GDSC_Skin_Cancer").in_("InProject").in_("SampleFor").in_("AliquotFor").in_("ResponseIn").out("ResponseTo").distinct("$._gid")
```
It would be much easier if there was an edge that connected the project to the drugs tested with an edge like `TestedInProject`. So the query
 ```
V("Project:GDSC_Skin_Cancer").in_("TestedInProject")
```
would find all the tested drugs.

**Comment by adamstruck** [comment]
Addressed in #312  and #313
