### ISSUE TITLE
Compound SB525334 or SB-525334?

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#360]
From #93 

> Should the name for compound SB52334 be SB525334 or SB-525334? It seems the name for this compound was misspelt at some dataset (e.g. GDSC), and adopted by other datasets or DBs?
> 
> The target gene for this compound is ALK5, its target pathway is RTK signaling, its PubCHEM ID is 9967941.
> 
> The profile for this compound at dockingfiles:
> http://dockingfiles.umh.es/anticancer-drugs/Anticancer_drugsview.asp?showdetail=&Id=77
> 
> The corresponding pubchem page for the compound:
> 
> https://pubchem.ncbi.nlm.nih.gov/compound/9967941
> 
> The misspelling of the compound name is also reflected in a benchmark dataset provided by Argonne National Laboratory Mathematics & Computer Science Division at:
http://ftp.mcs.anl.gov/pub/candle/public/benchmarks/Pilot1/combo/drug_info
> 
> ID NAME CLEAN_NAME SMILES INCHIKEY PUBCHEM
> GDSC.304 SB52334 SB52334 NULL NULL 9967941
>
> CTRP.445 SB-525334 SB525334 Cc1cccc(n1)-c1[nH]c(nc1-c1ccc2nccnc2c1)C(C)(C)C NULL 9967941
> 
> SB52334 and SB525334 have the same PubCHEM ID, but only the latter name (SB525334) has a corresponding PubCHEM page. Thus the name SB52334 / SB-52334 may be misspelt.

**Comment by adamstruck** [comment]
Confirmed that we still have no compound mapping for SB52334 in rc4 or the upcoming rc5 release.

**Comment by kellrott** [comment]
Not mapped in PharmacoDB: https://pharmacodb.pmgenomics.ca/drugs/614

**Comment by eleonora-ottina** [comment]
Are the two compounds SB52334 be SB525334 chemically identical?
