### ISSUE TITLE
Update BMEG schema descriptions to be a bit more descriptive

### ISSUE THREAD

**Issue by matthewpeterkort** [bmeg/bmeg-etl#386]
Most descriptions take the node type and rephrase it in less than 5 words. This description is flagged as "Too short". For example, https://github.com/bmeg/bmeg-etl/blob/develop/schema/gene.yaml#L3 gene.yaml description key is "A gene".

A description should be a brief description of the node type, enough to where somebody with only basic biological knowledge will know what the vertex is in the context of the schema. 1-2 sentences, 10-30 words. 

The below vertices have issues fulfilling this requirement:

allele: Description missing
allele_effect: Description missing
command: Too short
compound: Too short
copy_number_alteration: A little bit too short
drug_response: Too short 
exon: Too short
file: Too short
gene: Too short
gene_expression: A little bit too short
genomic_feature: Too short 
methylation: Too short 
methylation_prove: placeholder description
pathway: Too short
protein: Too short
protein_compound_association: placeholder description
protein_structure: Too short
publication: Too short 
somatic_callset: Too short
transcript: Too short
transcript_expression: Too short

**Comment by teslajoy** [comment]
##### Changes I made :
NOTE: need permission to make pull request

**Changed and added descriptions to:**
- **allele:** Description missing. 
- **allele_effect:** Description missing. 
- **command:** Description is too short. 
- **copy_number_alteration:** Description is a little bit too short. 
- **drug_response:** Description is too short. 
- **exon:** Description is too short. 
- **file:** Description is too short. 
- **gene:** Description is too short. 
- **genomic_feature:** Description is too short. 
- **methylation:** Description is too short. 
- **methylation_probe:** Description is too short. 
- **pathway:** Description is too short.
- **protein:** Description is too short. 
- **protein_structure:** Description is too short. 
- **publication:** Description is too short. 
- **somatic_callset:** Description is too short. 
- **transcript:** Description is too short. 
- **transcript_expression:** Description is too short. 

descriptions came from https://www.ebi.ac.uk/ols4/ or wikipedia 
can provide urls if interested. 

**Unchanged:**
- **compound:** Placeholder description.
- **protein_compound_association:** Placeholder description.
