### ISSUE TITLE
CCLE Transform Process

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#4]
- [x] Variants
- [x] Cell lines
- [x] Drug Response
- [x] Expression

**Comment by adamstruck** [comment]
Missing drug response data in latest build

**Comment by adamstruck** [comment]
We are producing DrugResponse vertices and DrugResponseIn edges: https://github.com/bmeg/bmeg-etl/blob/master/transform/gdsc/response.py

@kellrott can we close this?

**Comment by adamstruck** [comment]
GDSC has overlap with CCLE, but each project has its own drug response data.

**Comment by bwalsh** [comment]
^^ where is ccle specific drug response data?

**Comment by adamstruck** [comment]
https://data.broadinstitute.org/ccle_legacy_data/pharmacological_profiling/CCLE_NP24.2009_profiling_2012.02.20.csv
