### ISSUE TITLE
CTDD Import Process

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#8]

**Comment by bwalsh** [comment]
https://github.com/biostream/ctdd-transform

**Comment by adamstruck** [comment]
ftp://anonymous:guest@caftpd.nci.nih.gov/pub/OCG-DCC/CTD2/Broad/CTRPv2.0_2015_ctd2_ExpandedDataset/CTRPv2.0_2015_ctd2_ExpandedDataset.zip

**Comment by adamstruck** [comment]
Addressed in #279
