### ISSUE TITLE
Project Nodes

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#88]
Generate Project nodes to connect samples for 
 - [ ] All TCGA projects (TCGA-BRCA, TCGA-COAD, ... )
 - [ ] GTEX
 - [ ] CCLE

Might be able to use the `datasetId` value from Biosamples

**Comment by buchanae** [comment]
Would this include CTRP and CTDD?

**Comment by prismofeverything** [comment]
As I understand it, CTRP and CTDD refer to the CCLE samples and do not have
samples of their own. Happy to be corrected on this however.

**Comment by buchanae** [comment]
So this is intended to only connect Biosamples?

**Comment by prismofeverything** [comment]
Project nodes only connect to samples yes. Response curves connect to
samples and compounds.

**Comment by kellrott** [comment]
To find the different cohort vertices:
```
for i in O.aggregate(aql.term("datasets", "Biosample", "datasetId"))['datasets']['buckets']:
    print {"gid" : "cohort:%s" % i['key'], "label" : "Cohort"}
```

Getting the edges:
```
for row in O.query().V().where(aql.eq("_label", "Biosample")).render({"datasetId":"datasetId", "gid": "_gid"}):
    print {"from" : row['datasetId'], "to" : row["gid"], "label" : "hasSample"}
```
