### ISSUE TITLE
TCGA Fields to force to int

### ISSUE THREAD

**Issue by kellrott** [bmeg/bmeg-etl#90]
- birth_days_to
 - age_at_initial_pathologic_diagnosis
 - last_contact_days_to
 - initial_pathologic_dx_days_to
 - lymph_nodes_examined_count
 - lymph_nodes_examined_he_count
 - month_of_dcc_upload
 - form_completion_day
 - form_completion_year
 - initial_pathologic_dx_year
 - day_of_dcc_upload
 - year_of_dcc_upload
 - form_completion_month

**Comment by prismofeverything** [comment]
This is done and verified here: https://github.com/biostream/bmeg-etl/blob/master/bmeg.protograph.yaml#L52-L64

Will appear next time we trigger a rebuild.
